name: politicalIdeologiesDataPipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 12 3 * *' # Run once a month

jobs:
  politicalIdeologiesDataPipeline:
    name: Political Ideologies Data Pipeline
    runs-on: ubuntu-latest
    
    env:
      GOOGLE_AUTHENTICATION_CREDENTIALS: ${{ secrets.GOOGLE_AUTHENTICATION_CREDENTIALS }}
      GOOGLE_SPREADSHEET_URL: ${{ secrets.GOOGLE_SPREADSHEET_URL }}
      
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Pipeline
        run: |
          political_ideologies_tableau.py